export * from './hero/index'
export * from './services/index'
export * from './about/index'
export * from './contact/index'
export * from './technologies/index'
export * from './discovery/index'
export * from './teams/index'